#!/usr/bin/env python
#coding:utf8

import sys

def add():
    name = raw_input('Please input a name for this entry: ')
    port = raw_input('Please input the port number: ')
    ip = raw_input('Please input the ip address: ')
    password = raw_input('Please input the password: ')
    if not port.isdigit():
        raise Exception('Port is not a valid number.')
    return

def delete(id):
    pass

def use(id):
    pass

def show():
	pass


if __name__ == '__main__':
    mode = 'None'
    help = '''usage: ss-switch <operation>
Operations:
    add             add a new entry.
    delete value    delete an existed entry by ID.
    show            show all entries.
    use value       choose an entry by ID to use.'''
    if len(sys.argv)>1:
        mode = str(sys.argv[1]).lower()
    if mode in ['use','delete'] and len(sys.argv)<=2:
        print help
    elif mode in ['use','delete'] and str(sys.argv[2]).isdigit() == False:
        print help
    else:
    	if mode == 'add':
            add()
    	elif mode == 'delete':
            v = int(sys.argv[2])
            delete(v)
    	elif mode == 'show':
        	show()
    	elif mode == 'use':
            use(v)
        else:
            print help
